### ISSUE TITLE
Configuring with multiple hosts

### ISSUE THREAD

**Issue by amperesoft** [adamvduke/mod_interact#9]
Hi I have multiple hosts for which I want to configure this. It runs fine with single host but fails on multiple host with below mentioned error. FYI, I have removed logging from the code as it was giving me undef issue.

```
2015-05-22 16:24:47.827 [critical] <0.38.0>@gen_mod:start_module:90 Problem starting the module mod_offline_post for host <<"host2">>
 options: [{auth_token,<<"offline_post_auth_token">>},
           {post_url,<<"http://localhost:3000/services/offline_post1">>}]
 error: badarg
[{erlang,register,[mod_offline_post,<0.532.0>],[]},
 {mod_offline_post,start,2,[{file,"src/mod_offline_post.erl"},{line,45}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,82}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1323}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,67}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,269}]}]

```

My config file:

```
append_host_config:
  "host1":
    modules:
      mod_offline_post:
        auth_token: "offline_post_auth_token"
        post_url: "http://localhost:3000/services/offline_post"
  "host2":
    modules:
      mod_offline_post:
        auth_token: "offline_post_auth_token"
        post_url: "http://localhost:3000/services/offline_post1"
```

Any help is appreciated.
